#!/bin/sh
# postrm script for Ampache
set -e

. /usr/share/debconf/confmodule

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    remove)
	# Handling web server reconfiguration
	db_get ampache/configure-webserver
	webserver="apache2"
	restart=""

	for webserver in $webservers; do        
            webserver=${webserver%,}
        
            case "$webserver" in
		    apache2)
                    rm -f /etc/$webserver/conf.d/ampache
                    test -x /usr/sbin/$webserver || continue
                    restart="$restart $webserver"
                    ;;
                *)
                    ;;
            esac
        done
        
        db_get ampache/restart-webserver
        res="$RET"
        db_stop || true
        if [ "$res" = "true" ]; then
            for webserver in $restart; do
                webserver=${webserver%,}
                if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d $webserver restart
                else
                    /etc/init.d/$webserver restart
                fi
            done
        fi
    ;;
    purge)
#this is needed to remove ampache.cfg.php as it is added by the
#user and not removed during purge.
	rm -r -f /etc/ampache
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

#DEBHELPER#
