#!/bin/sh
# postinst script for Ampache

set -e

. /usr/share/debconf/confmodule

case "$1" in
    configure)	
	
# Handle webserver reconfiguration/restart ; stolen from zabbix package
	db_get ampache/configure-webserver || true
	webserver="apache2"
	restart=""

	for webserver in $webserver; do
            webserver=${webserver%,}
            test -x /usr/sbin/$webserver || continue
        
            if [ ! -f /etc/$webserver/conf.d/ampache ] && [ ! -h /etc/$webserver/conf.d/ampache ]; then
               ln -s /etc/ampache/ampache.conf /etc/$webserver/conf.d/ampache
            fi  
  
            restart="$restart $webserver"

        done

        db_get ampache/restart-webserver || true
	res="$RET"
	db_stop || true
	if [ "$res" = "true" ]; then
            for webserver in $restart; do
		webserver=${webserver%,}
		if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d $webserver restart
		else
                    /etc/init.d/$webserver restart
		fi
            done
	fi
	if [ -e /etc/ampache/ampache.cfg.php ]; then
	   cd /usr/share/ampache/www/bin
	   php /usr/share/ampache/www/bin/migrate_config.inc
	fi
    ;;
	*)	
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
	
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
#DEBHELPER#
